version: "3.7"

services:

  blog_api:
    image: kevcoxe/simple-flask-app
    container_name: blog_api
    restart: always
    environment:
      - PORT=5000
    expose:
      - 5000
    ports:
      - "5000:5000"

  # new_blog_frontend_react:
  #   build: ./new-blog-frontend
  #   container_name: new-blog-frontend-react
  #   restart: always
  #   expose:
  #     - 3000
  #   ports:
  #     - "3000:3000"

  # nginx:
  #   build: ./nginx
  #   container_name: nginx_for_blog
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - 'blogshare:/shared'


  # product_api:
  #   build: ./product_api
  #   container_name: product_api
  #   restart: always
  #   environment:
  #     - APP_NAME=ProductApi
  #   expose:
  #     - 8000

  # costomer_api:
  #   build: ./costomer_api
  #   container_name: costomer_api
  #   restart: always
  #   environment:
  #     - APP_NAME=CostomerApi
  #   expose:
  #     - 8000

  # nginx-react:
  #   build: ./nginx-react
  #   container_name: nginx-react
  #   restart: always
  #   ports:
  #     - "80:80"

# volumes:
#     blogshare:
#       driver: local
